// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeyp_u9lA1DTpNJzxZP2ygjUVrXZhGWE',
    appId: '1:556164901648:web:244e886962dd699e099395',
    messagingSenderId: '556164901648',
    projectId: 'kotoflow-35995',
    authDomain: 'kotoflow-35995.firebaseapp.com',
    storageBucket: 'kotoflow-35995.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOfkUcHqbY4FXaF535x0YUMlmjYtqbxc',
    appId: '1:556164901648:android:954200ec68539806099395',
    messagingSenderId: '556164901648',
    projectId: 'kotoflow-35995',
    storageBucket: 'kotoflow-35995.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc94ZCPQaXvQ_HHx7t6G-vVSFZQTOkkl0',
    appId: '1:556164901648:ios:8a52a27492a8c773099395',
    messagingSenderId: '556164901648',
    projectId: 'kotoflow-35995',
    storageBucket: 'kotoflow-35995.firebasestorage.app',
    iosBundleId: 'com.example.kotoFlowFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc94ZCPQaXvQ_HHx7t6G-vVSFZQTOkkl0',
    appId: '1:556164901648:ios:8a52a27492a8c773099395',
    messagingSenderId: '556164901648',
    projectId: 'kotoflow-35995',
    storageBucket: 'kotoflow-35995.firebasestorage.app',
    iosBundleId: 'com.example.kotoFlowFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzeyp_u9lA1DTpNJzxZP2ygjUVrXZhGWE',
    appId: '1:556164901648:web:d6d170d9b58e84fb099395',
    messagingSenderId: '556164901648',
    projectId: 'kotoflow-35995',
    authDomain: 'kotoflow-35995.firebaseapp.com',
    storageBucket: 'kotoflow-35995.firebasestorage.app',
  );
}
